# Generated by Django 4.2.4 on 2023-08-15 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_subscriptions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscriptions',
            new_name='Subscription',
        ),
    ]
