# Generated by Django 4.2.4 on 2023-08-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customuser_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='priceId',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
